wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.3
    framework: huggingface
    huggingface_version: 4.37.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709206460.924485
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 13
      - 19
      - 23
      4: 3.12.1
      5: 0.16.3
      6: 4.37.2
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 2.0e-05
batch_size:
  desc: null
  value: 16
epochs:
  desc: null
  value: 1000
